### ISSUE TITLE
Parse AMR

### ISSUE THREAD

**Issue by joe-xj** [ayyyq/TARA#5]
Dear author, thanks to the amazing work and open-sourced code. 
I'm puzzled by some of your treatment of the Parser AMR:
1. The first question is about the transition amr. First, I downloaded the "transition-amr-parser" folder and the "amr_general" folder, as mentioned in TSAR. Then, using the command "pip install transition-amr-parser" to download the required transition amr. However, when I run the "python amrparse.py" command, I get errors "no module of fairseq" and "ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+". For the above two errors, I run the command "pip install fairseq==0.10.2" and the command "pip install urllib3==1.26.15" respectively. However, when I run the "python amrparse.py" command, I still get "KeyError: 'stack_transformer_6x6_nopos' ", which occurs in the "amrparse.py" file with the line "parser = AMRParser.from_checkpoint(path)", seems to be related to the fairseq package. Has the author ever encountered this problem?

3. The second question is about AMRBART. May I ask if the data needs to be compressed after being parsed into AMR by AMRBART?

Thank u for your patience.

**Comment by ayyyq** [comment]
Hi, regarding the two issues you mentioned:
1. Please refer to [this repo](https://github.com/zhangzx-uiuc/AMR-IE#amr-parser) as mentioned in TSAR and follow the instructions (not just `pip install transition-amr-parser`) to install `transition-amr-parser`. Due to the old version of packages it requires, please handle any dependency conflicts carefully.
2. We have already integrated the compressed code into [data_processing/amrbart](https://github.com/ayyyq/TARA/blob/59621f6bfec9184d4a68572bfc74f7fd03d2984b/data_processing/amrbart/amr_parallel.py#L449), so there's no need to compress the parsed AMR again.

**Comment by joe-xj** [comment]
Thank you for your reply!!!
