### ISSUE TITLE
Inquiry regarding a specific step in your paper

### ISSUE THREAD

**Issue by GiveMeAnApple99** [ayyyq/TARA#7]
Dear author,
Thank you for this work.
I found the paper well-researched, however, I have a question regarding a specific point. In Section-2.2-**Missing spans**, the concept of "_**match**_" was mentiond, and I would like to seek further explanation to better understand it.

> If a generated span partially **matches** a node, we add a new node to represent this span and inherit connectives from the partially matched node. We also add a special edge between this node and the new node to indicate their overlap. If a generated span **fails to match** any existing nodes, we add a new node and connect it to the nearest nodes to its left and right with a special edge.

Or could you kindly provide guidance on which part of the **code** corresponds to the aforementioned steps?
Thank you very much for considering my inquiry.

**Comment by ayyyq** [comment]
Hi! Regarding your question, due to the presence of the AMR-text aligner, each node on the AMR graph already corresponds to a span in the text, denoted as s'_i'j'. Then, each candidate span proposed by the span proposal module is denoted as s_ij. If there exists an s'_i'j' such that i'=i and j'=j, we say that s_ij match the node corresponding to s'_i'j'. You can find the code [here](https://github.com/ayyyq/TARA/blob/59621f6bfec9184d4a68572bfc74f7fd03d2984b/src_wikievents/model.py#L402-L442).

**Comment by GiveMeAnApple99** [comment]
> Hi! Regarding your question, due to the presence of the AMR-text aligner, each node on the AMR graph already corresponds to a span in the text, denoted as s'_i'j'. Then, each candidate span proposed by the span proposal module is denoted as s_ij. If there exists an s'_i'j' such that i'=i and j'=j, we say that s_ij match the node corresponding to s'_i'j'. You can find the code [here](https://github.com/ayyyq/TARA/blob/59621f6bfec9184d4a68572bfc74f7fd03d2984b/src_wikievents/model.py#L402-L442).

Thanks a lot! Very kind of you!
I truly appreciate the time you took to clear up my confusion.😉
